### ISSUE TITLE
工程下载，打开后好多文件找到不到【报红】

### ISSUE THREAD

**Issue by ghost** [CustomPBWaters/Framework-Codeidea#1]
![123](https://user-images.githubusercontent.com/11734505/28244734-81c94c72-6a25-11e7-934f-a2f8752f29ad.png)
<img width="282" alt="321" src="https://user-images.githubusercontent.com/11734505/28244735-81dc2f7c-6a25-11e7-81c5-0d274cf098ef.png">

`怎么解决`

**Comment by CoderLNHui** [comment]
是我改了文件名字，现在可以了，欢迎你fork 提交合并
